In [2]:
import sys
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: D:\03_11\DATA\Miniconda

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    ca-certificates-2022.07.19 |       haa95532_0         123 KB
    certifi-2022.9.24          |   py39haa95532_0         154 KB
    conda-22.9.0               |   py39haa95532_0         888 KB
    intel-openmp-2021.4.0      |    haa95532_3556         2.2 MB
    mkl-2021.4.0               |     haa95532_640       114.9 MB
    mkl-service-2.4.0          |   py39h2bbff1b_0          51 KB
    mkl_fft-1.3.1              |   py39h277e83a_0         139 KB
    mkl_random-1.2.2           |   py39hf11a4ad_0         225 KB
    numpy-1.23.3               |   py39h3b20f71_0          11 KB
    numpy-base-1.23.3          |   py39h4da318b_0        

In [1]:
import numpy as np

**Задание 1**

In [4]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [5]:
a1 = a[0:, 0]
print(a1)
mean_a1 = np.mean(a1)
print(mean_a1)

[1 2 3 3 1]
2.0


In [6]:
a2 = a[0:, 1]
print(a2)
mean_a2 = np.mean(a2)
print(mean_a2)

[ 6  8 11 10  7]
8.4


In [7]:
mean_a = [mean_a1, mean_a2]
print(mean_a)

[2.0, 8.4]


**Задание 2**

In [8]:
a_centered = np.subtract(a, mean_a)
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


**Задание 3**

In [9]:
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1])
print(a_centered_sp)
rows, columns = a_centered.shape
print(rows)
a_centered_sp_divided = np.divide(a_centered_sp, rows - 1)
print(a_centered_sp_divided)

8.0
5
2.0


In [10]:
At = np.transpose(a)
At

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [11]:
cov = np.cov(At)
cov

array([[1. , 2. ],
       [2. , 4.3]])

**Тема “Работа с данными в Pandas”**


**Задание 1**

In [12]:
import sys
!conda install --yes --prefix {sys.prefix} pandas

Solving environment: ...working... done

## Package Plan ##

  environment location: D:\03_11\DATA\Miniconda

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.10.11 |       haa95532_0         125 KB
    ------------------------------------------------------------
                                           Total:         125 KB

The following packages will be UPDATED:

  ca-certificates                     2022.07.19-haa95532_0 --> 2022.10.11-haa95532_0 None




ca-certificates-2022 | 125 KB    |            |   0% 
ca-certificates-2022 | 125 KB    | #2         |  13% 
ca-certificates-2022 | 125 KB    | ########## | 100% 
ca-certificates-2022 | 125 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working..

In [13]:
import pandas as pd

In [14]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                       columns=['author_id', 'author_name'])
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [15]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [16]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[450, 300, 350, 500, 450, 370, 290]}, 
                    columns=['author_id', 'book_title', 'price'])
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [17]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [18]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3***

In [19]:
authors_price_sorted = authors_price.sort_values(by = 'price', ascending=False)

In [20]:
authors_price_sorted

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [21]:
top5 = authors_price_sorted.head()

In [22]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

**Задание 4**

In [23]:
price_agg = authors_price.groupby('author_name').agg({'price':'max'})
price_agg


price
author_name       
Островский     370
Тургенев       450
Чехов          500

In [24]:
price_agg = price_agg.reset_index()
price_agg = price_agg.rename(columns={'price':'max_price'})
price_agg

author_name  max_price
0  Островский        370
1    Тургенев        450
2       Чехов        500

In [25]:
price_agg1 = authors_price.groupby('author_name').agg({'price':'min'})
price_agg1

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [26]:
price_agg1 = price_agg1.reset_index()
price_agg1 = price_agg1.rename(columns={'price':'min_price'})
price_agg1

author_name  min_price
0  Островский        290
1    Тургенев        300
2       Чехов        450

In [27]:
authors_stat = pd.merge(price_agg, price_agg1, on = 'author_name', how = 'outer')
print(authors_stat)

  author_name  max_price  min_price
0  Островский        370        290
1    Тургенев        450        300
2       Чехов        500        450


In [28]:
authors_stat

author_name  max_price  min_price
0  Островский        370        290
1    Тургенев        450        300
2       Чехов        500        450

In [29]:
authors_stat['mean_price'] = (authors_stat['max_price'] + authors_stat['min_price']) // 2

In [30]:
authors_stat

author_name  max_price  min_price  mean_price
0  Островский        370        290         330
1    Тургенев        450        300         375
2       Чехов        500        450         475

In [31]:
authors_price ['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [33]:
?pd.pivot_table

In [42]:
book_info = pd.pivot_table(authors_price,
              index=["author_name"],
              values=["price"],
               columns=["cover"],
               aggfunc=[np.sum],
              fill_value=0)

In [43]:
book_info

sum        
             price        
cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

In [45]:
book_info.to_pickle('book_info.pkl')

In [46]:
book_info2=pd.read_pickle('book_info.pkl')

In [47]:
book_info2

sum        
             price        
cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950